### PR TITLE
Important Issue

### PR DESCRIPTION
**Pull request by witchica**
I am creating this PR to inform you that your fork of Tesla has become the official fork and to ask if you could transfer the repository to my github.

Thanks,
tattyseal
Tesla Ex-Developer

### CODE REVIEW

**Comment by cookta2012** [comment]
Are you saying that you wish to take over as the owner of the main REPO? sorry about not getting back to you until now.

**Comment by cookta2012** [comment]
If so could you briefly explain to me how this happened. I just want to understand because I see you have made commits to it and I rather try to be careful. @tattyseal

**Comment by witchica** [comment]
The original owners of the repository all decided it was best for it to be deleted and I think this one should also be deleted as it is now the main repo and we have all decided for it to be deleted, I can't link you to the issue as the repo was deleted.

**Comment by witchica** [comment]
By the way it is a PR because issues are disabled :+1:

**Comment by cookta2012** [comment]
Would you care to elaborate as to why. Is is unstable? what?

**Comment by cookta2012** [comment]
I also would like to know who the original repo owner was.

**Comment by witchica** [comment]
The original owner was ModForgery but the group fell apart and people were threatening to steal code etc. so I want to make sure there is no chance of that happening as it would cause alot of drama and copyright issues etc.

**Comment by witchica** [comment]
The group was also deleted.

**Pull request merged**
